### ISSUE TITLE
roProfile error!

### ISSUE THREAD

**Issue by maesaar** [cimendes/roProfile#4]
I was trying to use the script but got following error - could you help me?

```
python roProfile.py --roary ROARY/ --gffdir ROARY/
Logfile already exists! It will be overwritten...

parsing gene presence and absence file...
	pangenome size: 2114 genes
	core size: 1329 genes
		1 loci to be removed due to multiple alleles.. 
			...1 loci in core genome.. 
generating pan-genome frequency plot..
parsing gff files...
Reading... 
	.DS_Store
Traceback (most recent call last):
  File "roProfile.py", line 490, in <module>
    main()
  File "roProfile.py", line 460, in main
    sequenceDict, coregenes, removedSize=parserGFF(args.gffdir, profileDict, args.threshold, coregenes)
  File "roProfile.py", line 177, in parserGFF
    for genegroup, gene in profileDict[filename].items():
KeyError: '.DS_Store'
```

Thanks

**Comment by cimendes** [comment]
Hello!

I've never came across that error before. Could you share with me the command you're using? It seems like there's a hidden folder/file called .SD_Store in the input gff folder. Are you running it in a Mac OS?

**Comment by maesaar** [comment]
I had Roary output and *.gff files in same folder. As soon as I moved *.gff files in a separate folder the script worked as should!

**Comment by cimendes** [comment]
I've pushed a few alterations in the dev branch that should, hopefully, fix this issue. Thank you for the feedback! :)
